### ISSUE TITLE
How do you get the nice drracket colors in your gifs?

### ISSUE THREAD

**Issue by mlavrent** [sorawee/fishy-completion#2]
How do you get the nice colors in your gifs? Whenever I try a dark theme, it never colors the command bar/scroll bars, leaving a dark editor and repl field with light outlines (on windows). Running drracket 7.5

(not an issue, just a question!)

**Comment by sorawee** [comment]
Oh, this is the dark mode feature of DrRacket, which is not available on Windows. See https://github.com/racket/drracket/issues/235#issuecomment-619301761 and subsequent comments.

EDIT: or https://github.com/racket/gui/issues/197

**Comment by mlavrent** [comment]
Ok thanks :( .
